== Preamble

=== Abstract

A Semantic Web data model of roads information. It caters specifically for Australian & New Zealand's road labelling (naming) needs.

[NOTE]
This model was made for Queensland Spatial Information, a unit of the Queensland Department of Resources, to assist with their future address and roads database design. It is a Component Model of their 'QSI Supermodel' which includes models for Address, Place Name and Cadastral information which are all designed to work together, however they may all be used independently too.

=== Namespaces

This model is built on a small set of well-regarded Semantic Web models which use a variety of namespacess. Prefixes for these namespaces, used throughout this document, are listed below.

[width=100%, frame=none, grid=none, cols="1,4,5"]
|===
|Prefix | Namespace | Description

| `*:*` | `*https://linked.data.gov.au/def/roads/*` | *This model*
| `cn` | `https://linked.data.gov.au/def/cn/` | Compound Name Model
| `dcterms` | `http://purl.org/dc/terms/` | Dublin Core Terms
| `ex` | `http://example.com/` | Generic examples
| `geo` | `http://www.opengis.net/ont/geosparql#` | OGC GeoSPARQL model
| `lm` | `https://linked.data.gov.au/def/lifecycle/` | Lifecycle Model
| `owl` | `http://www.w3.org/2002/07/owl#` | Web Ontology Language ontology
| `rdfs` | `http://www.w3.org/2000/01/rdf-schema#` | RDF Schema ontology
| `sosa` | `http://www.w3.org/ns/sosa/` | Sensor, Observation, Sample, and Actuator ontology
| `skos` | `http://www.w3.org/2004/02/skos/core#` | Simple Knowledge Organization System (SKOS) ontology
| `time` | `http://www.w3.org/2006/time#` | Time Ontology in OWL
| `void` | `http://rdfs.org/ns/void#` | Vocabulary of Interlinked Data (VoID) ontology
| `xsd` | `http://www.w3.org/2001/XMLSchema#` | XML Schema Definitions ontology
|===

=== Conformance

This model conforms to the https://w3id.org/profile/ontpub[OntPub Profile] which is a specification for ontology publication that mandates certain structural and metadata properties for the model as a whole and model elements. Metadata elements for the model as a whole - the ontology - are given in the <<Metadata>> section above.

==== Figures

Figures used in this document use the following key:

[[fig-figure-key]]
.Key of elements used in this Model's figures
image::img/Key.svg[width="15%"]

==== Example Data
Example Data used in this document, for instance in model element "Example" values, are https://www.w3.org/RDF/[RDF] data in the https://www.w3.org/TR/turtle/[Turtle] syntax.