== Supporting Vocabularies



This model depends on several vocabularies to give specific values to typing properties for `FeatureLabelComponent`, `LifecycelStage` and so on. Only one of those vocabularies is defined here - <<Feature Label Component Types for Roads>>. All other vocabularies are defined in the Feature Labelling Model <<FL>>.

=== Feature Label Component Types for Roads

This vocabulary is a specialised form of <<ISO19160-1>>'s `AddressComponentType` vocabulary. The original 8 concepts from that standard are not included as they apply either to addresses or provide only one component type for roads - `thoroughfareName.

|===
| IRI | Name | Description | Status | Expected Form | Usage directive

| `rct:RoadPrefix` | Road Prefix | A literal initial part of a road's label that comes before the road's name | original | literal | Use
| `rct:RoadName` | Road Name | The literal name of the road, without any expression of the road's type | original | literal | Use
| `rct:RoadType` | Road Type | A reference to the type of the road, selected from a controlled list of road (street) types | original | object reference | Use
| `rct:RoadSuffix` | Road Suffix | A literal initial part of a road's label that comes after the road's name and type value | original | literal | Use
|===

This vocabulary is available in machine-readable form at *https://linked.data.gov.au/def/rct*.

Three of the four elements above are literal values, e.g. a Road Name of "Yundah". The exception is Road Type which sould be a reference to a Road (Street) Type controlled vocabulary object, such as an instance of a Concepts from Australia's ICSM's _StreetTypes_ vocabulary. A textual representation for Road Type can be acquired from such an object by importing one of its potentially many labels.
