= Spatial Information Queensland - Roads Model

This Model is Spatial Information Queensland's model for roads data and also a candidate model for all Australian & New Zealand roads.

== Metadata

[width=75%, frame=none, grid=none, cols="1,5"]
|===
|**IRI** | https://linked.data.gov.au/def/roads-model/guidance
|**Title** | Roads Model
|**Description** |This document is both the front page of the Queensland Land Information Roads Model's repository and a _Guidance document_ and introduces all the other elements of the Roads Model.
|**Created** | 2022-04-01
|**Modified** | 2023-05-02
|**Issued** | 0000-00-00
|**Creator** | Consortium through https://frontiersi.com.au[Frontier SI]
|**Publisher** | https://linked.data.gov.au/org/qsi[Queensland Spatial Information]
|**License** | https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International (CC BY 4.0)]
|===

This model's document is auto-built from the source file `00-master.adoc` and is viewable online at:

* https://linked.data.gov.au/def/roads-model[QSI Roads Model]

The repository is at:

* https://github.com/Spatial-Information-QLD/roads-model

To contribute to this document, see link:https://github.com/Spatial-Information-QLD/address-model/blob/main/editing.adoc[editing instructions] on how to set up the editing environment.

=== Building Locally

To build this model's documentation locally, you need to use the AsciDoctor builder for ASCIIDOC documents:

```
asciidoctor 00-master.adoc > model.html
```

== Rights and License

Content generated by Spatial Information Queensland is copyright as follows:

&copy; The State of Queensland (Department of Resources) 2023

This information is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.

Much of the vocabulary content here is copied from elsewhere and, where this has occurred, the vocabulary source is noted so that the source information licensing and rights may be discovered.

== Contacts

For more information about these vocabularies, contact:

*Spatial Information* +
GeoResources Division +
Department of Resources +  
Queensland Government +
CadastralAdminDataHelp@resources.qld.gov.au 

For further information, please visit:

https://www.resources.qld.gov.au/data-mapping +  
https://qldspatial.information.qld.gov.au/

For technical model implementation questions, contact:

*Nicholas Car* +
nick@kurrawong.ai +
_Contractor to Spatial Information Qld._
